// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(TreeContext))]
    [Migration("20240502051505_NewName")]
    partial class NewName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.dbColonies", b =>
                {
                    b.Property<int>("IdColony")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColony"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("IdColony");

                    b.ToTable("Colonies");
                });

            modelBuilder.Entity("Entities.dbSpecies", b =>
                {
                    b.Property<int>("IdSpecie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSpecie"));

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("scientificName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdSpecie");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Entities.dbTreeMap", b =>
                {
                    b.Property<int>("IdTree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTree"));

                    b.Property<int>("ColonyIdColony")
                        .HasColumnType("int");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<int>("EFC")
                        .HasColumnType("int");

                    b.Property<int>("EFT")
                        .HasColumnType("int");

                    b.Property<int>("ESC")
                        .HasColumnType("int");

                    b.Property<int>("EST")
                        .HasColumnType("int");

                    b.Property<int>("IdColony")
                        .HasColumnType("int");

                    b.Property<int>("IdSpecie")
                        .HasColumnType("int");

                    b.Property<int>("Risk")
                        .HasColumnType("int");

                    b.Property<int>("Sa")
                        .HasColumnType("int");

                    b.Property<int>("SpecieIdSpecie")
                        .HasColumnType("int");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<int>("Xcoordinate")
                        .HasColumnType("int");

                    b.Property<int>("Ycoordinate")
                        .HasColumnType("int");

                    b.HasKey("IdTree");

                    b.HasIndex("ColonyIdColony");

                    b.HasIndex("SpecieIdSpecie");

                    b.ToTable("TreeMap");
                });

            modelBuilder.Entity("Entities.dbTreeMap", b =>
                {
                    b.HasOne("Entities.dbColonies", "Colony")
                        .WithMany("Trees")
                        .HasForeignKey("ColonyIdColony")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.dbSpecies", "Specie")
                        .WithMany("Trees")
                        .HasForeignKey("SpecieIdSpecie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colony");

                    b.Navigation("Specie");
                });

            modelBuilder.Entity("Entities.dbColonies", b =>
                {
                    b.Navigation("Trees");
                });

            modelBuilder.Entity("Entities.dbSpecies", b =>
                {
                    b.Navigation("Trees");
                });
#pragma warning restore 612, 618
        }
    }
}
